### PR TITLE
Add "optionally download quizzes" feature

### PR DESCRIPTION
**Pull request by esidate**
Adding -z or --quizzes flag will download quizzes too.
Quizzes are downloaded in JSON format.
We can later add a script to parse those JSON files and give the user an interactive GUI using [PyInquirer](https://github.com/CITGuru/PyInquirer) and [Click](https://click.palletsprojects.com).

### CODE REVIEW

**Comment by r0oth3x49** [comment]
@thehunckerma do you think downloading quizzes is good?

**Comment by thehunckerma** [comment]
Hello @r0oth3x49
I'm not sure what do you mean by good but in my case i needed to have the quizzes too, to test my knowledge obviously.
I was willing to write the code for it anyways, i just thought it would be cool to make a pull request out of it.
After all it's an optional feature, merging it wouldn't do any harm and it's been tested on 145 courses (by myself).

**Comment by esidate** [comment]
Hello @r0oth3x49 will you merge this anytime soon ?

**Comment by r0oth3x49** [comment]
@esidate sorry for the very late response would be great if you can fix the conflicts and make another pull request so that i can merge it.

**Comment by esidate** [comment]
@r0oth3x49 Hello, my pull request was pending for 4 months and now i have to merge it with a 5 days old pull request.
That's unfortunate.

**Comment by ibrahimjelliti** [comment]
@esidate I pulled your PR, the quiz data is not downloaded. I always got the `content` array empty in the quiz JSON file

**Comment by esidate** [comment]
Hello @ibrahimjelliti that's because another pull request that was made 4 months after mine was merged first.

**Pull request closed without merging**
